version: "3.8"

services:
  checkloading_db:
      image: postgres:12.11
      volumes: 
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: anton
        POSTGRES_DB: checkloading_db
      ports:
        - "5432:5432"
  checksloading_web:
    restart: on-failure
    build: .
    volumes:
      - .:/code/src/checkloading
    command: bash -c "python checksloading/manage.py migrate && python checksloading/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - checkloading_db
    environment:
      SECRET_KEY: django-insecure-1smtc!loc!aa-r0t2t=(j8u#(09!f()j4)6q4u%q@ujge7t^@s
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: checkloading_db
      DB_USER: anton
      DB_PASSWORD: pass
      DB_HOST: checkloading_db
      DB_PORT: 5432
  checksloading_test:
    restart: on-failure
    build: .
    volumes:
      - .:/code/src/checkloading
    command: bash -c "cd checksloading && pytest"
    environment: 
      DJANGO_SETTINGS_MODULE: checksloading.settings
    depends_on:
      - checkloading_db
volumes: 
  postgres_data: