# Generated by Django 4.0.5 on 2022-07-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(max_length=50)),
                ('check_issuance_time', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('customer_id', models.CharField(max_length=255)),
                ('pos_id', models.CharField(max_length=255)),
            ],
        ),
    ]
