# Generated by Django 4.0.5 on 2022-07-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkloading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='customer_id',
            field=models.CharField(max_length=20),
        ),
    ]
