# Generated by Django 4.0.5 on 2022-07-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkloading', '0003_alter_check_check_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='check_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='pos_id',
            field=models.CharField(max_length=20),
        ),
    ]
