# Generated by Django 4.0.5 on 2022-07-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkloading', '0005_alter_check_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='check',
            table='Checks',
        ),
    ]
