# Generated by Django 4.0.5 on 2022-07-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkloading', '0006_alter_check_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='check',
            table='checks',
        ),
    ]
