version: "3.8"

services:
  checkloading_db:
      image: postgres:12.11
      volumes: 
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: anton
        POSTGRES_DB: checkloading_db
      ports:
        - "5432:5432"
  checksloading_web:
    build: .
    volumes:
      - .:/code/src/checkloading
    command: bash -c "python /code/src/checkloading/manage.py migrate && python /code/src/checkloading/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - checkloading_db
volumes: 
  postgres_data: